### ISSUE TITLE
各位现在还能正常使用么 取经？

### ISSUE THREAD

**Issue by Hikarux1002** [studyhelperhelper/studyhelper#374]
用的2.37版本，今天开始强制跳窗 不更新直接退出到页面 那位还在正常使用么 取经下

**Comment by nihaolixin** [comment]
我更新到2.4的版本，是正常能用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 上午8:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[studyhelperhelper/studyhelper] 各位现在还能正常使用么 取经？ (Issue #374)





 
用的2.37版本，今天开始强制跳窗 不更新直接退出到页面 那位还在正常使用么 取经下

**Comment by Hikarux1002** [comment]
> 我更新到2.4的版本，是正常能用的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "studyhelperhelper/studyhelper" ***@***.***&gt;; 发送时间:&nbsp;2022年11月10日(星期四) 上午8:27 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[studyhelperhelper/studyhelper] 各位现在还能正常使用么 取经？ (Issue #374) 用的2.37版本，今天开始强制跳窗 不更新直接退出到页面 那位还在正常使用么 取经下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感觉2.4早晚也会被和谐

**Comment by nihaolixin** [comment]
暂时能用的，先用着呗。实在没办法了在想其他办法吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "studyhelperhelper/studyhelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 上午8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [studyhelperhelper/studyhelper] 各位现在还能正常使用么 取经？ (Issue #374)





  
我更新到2.4的版本，是正常能用的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "studyhelperhelper/studyhelper" @.&gt;; 发送时间:&nbsp;2022年11月10日(星期四) 上午8:27 @.&gt;; @.&gt;; 主题:&nbsp;[studyhelperhelper/studyhelper] 各位现在还能正常使用么 取经？ (Issue #374) 用的2.37版本，今天开始强制跳窗 不更新直接退出到页面 那位还在正常使用么 取经下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
感觉2.4早晚也会被和谐

**Comment by GaviTate** [comment]
> 我更新到2.4的版本，是正常能用的
2.4版的答题能拿分吗

**Comment by shaozongjie** [comment]
是不是强制更新，没法用了

**Comment by s1n1209** [comment]
> 我更新到2.4的版本，是正常能用的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "studyhelperhelper/studyhelper" ***@***.***&gt;; 发送时间:&nbsp;2022年11月10日(星期四) 上午8:27 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[studyhelperhelper/studyhelper] 各位现在还能正常使用么 取经？ (Issue #374) 用的2.37版本，今天开始强制跳窗 不更新直接退出到页面 那位还在正常使用么 取经下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2.4可以分享一下吗，在哪里可以下载

**Comment by studyhelperhelper** [comment]
已更新
